### ISSUE TITLE
help using color scale

### ISSUE THREAD

**Issue by jbielski** [santilland/plotty#21]
Hi,

I have a tif that I would like to use the 'rainbow' color scale with. The tif's "data" are pixels with integer values from 1 to 7. The tif's "nodata" pixels have a value of 127. When I use 'rainbow' like in the following, my tif contains greens and blues, but no reds or yellows:

                    rendererOptions = {
                        "renderer": L.LeafletGeotiff.plotty({
                            displayMin: 0,
                            displayMax: 10,
                            clampLow: true,
                            clampHigh: false,
                            domain: [1, 7],
                            colorScale: 'rainbow'
                        })
                    }
                    var geotiff_layer = L.leafletGeotiff(url, rendererOptions).addTo(map);

I tried creating my own color scale with rainbow colors as well. I saw different colors, but the colors were muted, almost as if there was a non-zero alpha. So red looked pink. Setting opacity and fillOpacity to 0.0 in the rendererOptions did not fix that problem:
plotty.addColorScale("mycolorscale", ["#bc0f0f", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00", "#ffff33", "#a65628"], [0, 0.15, 0.3, 0.45, 0.6, 0.75, 1.0]);

What should I do to see the full range of rainbow colors in my tif using plotty?

**Comment by santilland** [comment]
Hello jbielski,

first off for you are using another library (LeafletGeotiff) that is in then using this library, so any kind of change could be happening of which i have no control or knowledge of, so i would recommend that you generally ask or report issues in the library you are using.
That aside i guess you are having issues because you have integer values, the colorscale does not have discrete steps, it interpolates between steps, if you have a look at the rainbow colorscale below you will see that for example  yellow will be around the value 5.5, so if you only have values of 5 and 6 (integers) you will never see the color yellow.
![image](https://user-images.githubusercontent.com/4036819/80189375-dc31b580-8612-11ea-85da-2bdfb6f6d18f.png)
For setting color to basically just 7 values (so 7 colors, you probably don't even need plotty) you can manually assign each value a color.

**Comment by jbielski** [comment]
Oh, sorry, I thought I needed to use plotty to add any color to my TIF. I'm kind of new to this, can you explain how would I set the colors directly?

**Comment by santilland** [comment]
Hi, i simplified things a bit. Plotty does not have a way of rendering discrete colors for integer values values.
I meant you could relatively easy use a canvas element to render a colored pixel based on the 7 values you have in your tiff, but as you are using this to visualize something on leaflet with another library i couldn't really tell. I'm not even sure what colors you expect to have.
Ok, so the only thing i can think of is that you create your own colorscale where you make sure your integer values represent exactly the color you want to have.
So if you have values from 1 to 7, make sure to do percentage steps repeating the color so that each integer represents the color you want, something like....:
```
plotty.addColorScale(
    "mycolorscale", 
    [
        "#1colorhex", "#1colorhex",
        "#2colorhex", "#2colorhex",
        "#3colorhex", "#3colorhex", ... // this for 7 values so 14 steps
    ],
    [
        0, 0.144, // "big" same color step (0 to 0.144)
        0.145, 0.288, //  and "small" color step to change to next color (0.144 to 0.145) and so on 
        0.432, 0.433,
       ...
    ]
);
```

**Comment by jbielski** [comment]
I was trying to use this:
plotty.addColorScale("mycolorscale", ["#bc0f0f", "#377eb8", "#4daf4a", "#984ea3", "#ff7f00", "#ffff33", "#a65628"], [0, 0.15, 0.3, 0.45, 0.6, 0.75, 1.0]);

**Comment by santilland** [comment]
Yes you said that before, did you try to do what i said?

**Comment by jbielski** [comment]
I did, it worked! Thank you.

**Comment by santilland** [comment]
Nice, glad to hear, i'll close the ticket now, bye!

**Comment by santilland** [comment]
Actually @jbielski could you still post your solution in case anyone wanted to do the same in the future?

**Comment by jbielski** [comment]
Yes.  This scale maps (approximately) 7 integer pixel values to 7 colors:
                plotty.addColorScale("mycolorscale",
                    [
                        "#e41a1c", "#e41a1c",
                        "#377eb8", "#377eb8",

                        "#ffff33", "#ffff33", // yellow

                        "#984ea3", "#984ea3",
                        "#ff7f00", "#ff7f00",
                        "#4daf4a", "#4daf4a", // green. this is for 7 values, so 14 steps


                        "#a65628", "#a65628"
                    ],
                    [
                        0, 0.144, // "big" same color step (0 to 0.144)
                        0.145, 0.288, //  and "small" color step to change to next color (0.144 to 0.145) and so on
                        0.289, 0.432, 
                        0.433, 0.578,
                        0.579, 0.730,
                        0.731, 0.878,
                        0.879, 1.0
                    ]);
